# Generated by Django 2.2.5 on 2021-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japhlu_app', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
