# Generated by Django 2.2.5 on 2021-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japhlu_app', '0006_auto_20210209_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
