# Generated by Django 2.2.5 on 2021-02-09 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japhlu_app', '0007_auto_20210209_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
