# Generated by Django 2.2.5 on 2021-02-11 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japhlu_app', '0008_auto_20210209_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
